run:
  concurrency: 8
  deadline: 10m
  issues-exit-code: 1
  tests: false

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - errors
  goimports:
    local-prefixes: github.com/teamdbnn/go-yandex-contest
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  unparam:
    check-exported: true

linters:
  enable:
  - depguard
  - errcheck
  - gocritic
  - gocyclo
  - gofmt
  - goimports
  - revive
  - gosec
  - govet
  - ineffassign
  - interfacer
  - misspell
  - nakedret
  - prealloc
  - exportloopref
  - staticcheck
  - stylecheck
  - unconvert
  - unparam

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: model.go
      linters:
        - unused
