package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// DetailedRunReport DetailedRunReport
//
// swagger:model DetailedRunReport
type DetailedRunReport struct {

	// compile log
	// Required: true
	CompileLog *string `json:"compileLog"`

	// compiler
	// Required: true
	Compiler *string `json:"compiler"`

	// diff
	// Required: true
	Diff *string `json:"diff"`

	// problem alias
	// Required: true
	ProblemAlias *string `json:"problemAlias"`

	// problem Id
	// Required: true
	ProblemID *string `json:"problemId"`

	// source
	// Required: true
	Source *string `json:"source"`

	// submission time
	// Required: true
	SubmissionTime *string `json:"submissionTime"`

	// verdict
	// Required: true
	Verdict *string `json:"verdict"`
}
