package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// DirectoryPackageAllOf1 DirectoryPackage
//
// swagger:model directoryPackageAllOf1
type DirectoryPackageAllOf1 struct {

	// name
	Name string `json:"name,omitempty"`

	packagesField []FileSystemPackage
}
