package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// DirectoryPackage DirectoryPackage
//
// swagger:model DirectoryPackage
type DirectoryPackage struct {
	nameField string

	DirectoryPackageAllOf1
}
