package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Duration Duration
//
// swagger:model Duration
type Duration struct {

	// millis
	Millis int64 `json:"millis,omitempty"`

	// standard days
	StandardDays int64 `json:"standardDays,omitempty"`

	// standard hours
	StandardHours int64 `json:"standardHours,omitempty"`

	// standard minutes
	StandardMinutes int64 `json:"standardMinutes,omitempty"`

	// standard seconds
	StandardSeconds int64 `json:"standardSeconds,omitempty"`
}
