package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Event Event
//
// swagger:model Event
type Event struct {

	// absolute time
	AbsoluteTime int64 `json:"absoluteTime,omitempty"`

	// contest time
	ContestTime int64 `json:"contestTime,omitempty"`
}
