package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ExternalID ExternalId
//
// swagger:model ExternalId
type ExternalID struct {

	// client Id
	// Required: true
	ClientID *string `json:"clientId"`

	// empty
	// Required: true
	Empty *bool `json:"empty"`

	// id
	ID string `json:"id,omitempty"`
}
