package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// ExternalLog ExternalLog
//
// swagger:model ExternalLog
type ExternalLog struct {

	// contest log
	ContestLog *ContestLog `json:"contestLog,omitempty"`

	// contest log key
	ContestLogKey []string `json:"contestLogKey"`

	// download start time
	// Format: date-time
	DownloadStartTime strfmt.DateTime `json:"downloadStartTime,omitempty"`

	// dynamic
	Dynamic bool `json:"dynamic,omitempty"`

	// dynamic Url
	DynamicURL string `json:"dynamicUrl,omitempty"`

	// events count
	EventsCount int32 `json:"eventsCount,omitempty"`

	// id
	// Required: true
	ID *int64 `json:"id"`

	// import as internal
	ImportAsInternal bool `json:"importAsInternal,omitempty"`

	// last update
	// Format: date-time
	LastUpdate strfmt.DateTime `json:"lastUpdate,omitempty"`

	// last update attempt
	// Format: date-time
	LastUpdateAttempt strfmt.DateTime `json:"lastUpdateAttempt,omitempty"`

	// last update error
	LastUpdateError []string `json:"lastUpdateError"`

	// owner Id
	OwnerID []int64 `json:"ownerId"`

	// raw Xml log
	// Format: byte
	RawXMLLog strfmt.Base64 `json:"rawXmlLog,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// xml log key
	XMLLogKey []string `json:"xmlLogKey"`
}
