package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
)

// FileSystemPackage FileSystemPackage
//
// swagger:discriminator FileSystemPackage type
type FileSystemPackage interface {
	runtime.Validatable
	runtime.ContextValidatable

	// name
	Name() string
	SetName(string)

	// AdditionalProperties in base type shoud be handled just like regular properties
	// At this moment, the base type property is pushed down to the subtype
}

type fileSystemPackage struct {
	nameField string
}

// Name gets the name of this polymorphic type
func (m *fileSystemPackage) Name() string {
	return m.nameField
}

// SetName sets the name of this polymorphic type
func (m *fileSystemPackage) SetName(val string) {
	m.nameField = val
}
