package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
)

// FilePackageAllOf1 FilePackage
//
// swagger:model filePackageAllOf1
type FilePackageAllOf1 struct {

	// data
	// Format: binary
	Data io.ReadCloser `json:"data,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}
