package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// GrantResponse GrantResponse
//
// swagger:model GrantResponse
type GrantResponse struct {

	// roles
	// Required: true
	Roles []*ExtendedRole `json:"roles"`
}
