package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// IDPrincipal Id«Principal»
//
// swagger:model Id«Principal»
type IDPrincipal struct {

	// checked Id
	// Required: true
	CheckedID *int64 `json:"checkedId"`

	// checked raw external Id
	// Required: true
	CheckedRawExternalID *string `json:"checkedRawExternalId"`

	// external Id
	// Required: true
	ExternalID *ExternalID `json:"externalId"`

	// id
	ID int64 `json:"id,omitempty"`

	// model
	// Required: true
	Model *KClassPrincipal `json:"model"`

	// new
	// Required: true
	New *bool `json:"new"`

	// raw external Id
	RawExternalID string `json:"rawExternalId,omitempty"`

	// uid
	// Format: uuid
	UID strfmt.UUID `json:"uid,omitempty"`
}
