package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// JSONNode JsonNode
//
// swagger:model JsonNode
type JSONNode struct {

	// array
	Array bool `json:"array,omitempty"`

	// big decimal
	BigDecimal bool `json:"bigDecimal,omitempty"`

	// big integer
	BigInteger bool `json:"bigInteger,omitempty"`

	// binary
	Binary bool `json:"binary,omitempty"`

	// boolean
	Boolean bool `json:"boolean,omitempty"`

	// container node
	ContainerNode bool `json:"containerNode,omitempty"`

	// double
	Double bool `json:"double,omitempty"`

	// empty
	Empty bool `json:"empty,omitempty"`

	// float
	Float bool `json:"float,omitempty"`

	// floating point number
	FloatingPointNumber bool `json:"floatingPointNumber,omitempty"`

	// int
	Int bool `json:"int,omitempty"`

	// integral number
	IntegralNumber bool `json:"integralNumber,omitempty"`

	// long
	Long bool `json:"long,omitempty"`

	// missing node
	MissingNode bool `json:"missingNode,omitempty"`

	// node type
	// Enum: [ARRAY BINARY BOOLEAN MISSING NULL NUMBER OBJECT POJO STRING]
	NodeType string `json:"nodeType,omitempty"`

	// null
	Null bool `json:"null,omitempty"`

	// number
	Number bool `json:"number,omitempty"`

	// object
	Object bool `json:"object,omitempty"`

	// pojo
	Pojo bool `json:"pojo,omitempty"`

	// short
	Short bool `json:"short,omitempty"`

	// textual
	Textual bool `json:"textual,omitempty"`

	// value node
	ValueNode bool `json:"valueNode,omitempty"`
}
