package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// KParameter KParameter
//
// swagger:model KParameter
type KParameter struct {

	// annotations
	// Required: true
	Annotations []Annotation `json:"annotations"`

	// index
	// Required: true
	Index *int32 `json:"index"`

	// kind
	// Required: true
	// Enum: [INSTANCE EXTENSION_RECEIVER VALUE]
	Kind *string `json:"kind"`

	// name
	Name string `json:"name,omitempty"`

	// optional
	// Required: true
	Optional *bool `json:"optional"`

	// type
	// Required: true
	Type *KType `json:"type"`

	// vararg
	// Required: true
	Vararg *bool `json:"vararg"`
}
