package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// KTypeProjection KTypeProjection
//
// swagger:model KTypeProjection
type KTypeProjection struct {

	// type
	Type *KType `json:"type,omitempty"`

	// variance
	// Enum: [INVARIANT IN OUT]
	Variance string `json:"variance,omitempty"`
}
