package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// KType KType
//
// swagger:model KType
type KType struct {

	// annotations
	// Required: true
	Annotations []Annotation `json:"annotations"`

	// arguments
	// Required: true
	Arguments []*KTypeProjection `json:"arguments"`

	// classifier
	Classifier KClassifier `json:"classifier,omitempty"`

	// marked nullable
	// Required: true
	MarkedNullable *bool `json:"markedNullable"`
}
