package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Message Message
//
// swagger:model Message
type Message struct {

	// answers
	Answers []string `json:"answers"`

	// problem
	Problem string `json:"problem,omitempty"`

	// question
	Question string `json:"question,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`
}
