package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Messages Messages
//
// swagger:model Messages
type Messages struct {

	// messages
	Messages []*Message `json:"messages"`
}
