package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ParticipantStatus ParticipantStatus
//
// swagger:model ParticipantStatus
type ParticipantStatus struct {

	// contest duration
	ContestDuration string `json:"contestDuration,omitempty"`

	// contest finish time
	ContestFinishTime string `json:"contestFinishTime,omitempty"`

	// contest infinite
	ContestInfinite bool `json:"contestInfinite,omitempty"`

	// contest start time
	ContestStartTime string `json:"contestStartTime,omitempty"`

	// contest state
	ContestState string `json:"contestState,omitempty"`

	// participant finish time
	ParticipantFinishTime string `json:"participantFinishTime,omitempty"`

	// participant left time
	ParticipantLeftTime string `json:"participantLeftTime,omitempty"`

	// participant name
	ParticipantName string `json:"participantName,omitempty"`

	// participant start time
	ParticipantStartTime string `json:"participantStartTime,omitempty"`

	// roles
	Roles []string `json:"roles"`
}
