package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Participant Participant
//
// swagger:model Participant
type Participant struct {

	// contest
	Contest *Contest `json:"contest,omitempty"`

	// contest started
	ContestStarted bool `json:"contestStarted,omitempty"`

	// creation time
	CreationTime []int64 `json:"creationTime"`

	// deleted
	// Required: true
	Deleted *bool `json:"deleted"`

	// displayed name
	DisplayedName string `json:"displayedName,omitempty"`

	// displayed name checked
	DisplayedNameChecked string `json:"displayedNameChecked,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// login
	Login string `json:"login,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// name auto generated
	NameAutoGenerated bool `json:"nameAutoGenerated,omitempty"`

	// not deleted
	// Required: true
	NotDeleted *bool `json:"notDeleted"`

	// start time
	// Format: date-time
	StartTime strfmt.DateTime `json:"startTime,omitempty"`

	// team
	Team *Team `json:"team,omitempty"`

	// team participation
	TeamParticipation bool `json:"teamParticipation,omitempty"`

	// teammates
	Teammates []*User `json:"teammates"`

	// user
	User *User `json:"user,omitempty"`

	// user Id
	UserID int64 `json:"userId,omitempty"`

	// user ids
	UserIds []int64 `json:"userIds"`
}
