package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Role Role
//
// swagger:model Role
type Role struct {

	// checked Id
	CheckedID int64 `json:"checkedId,omitempty"`

	// checked raw external Id
	CheckedRawExternalID string `json:"checkedRawExternalId,omitempty"`

	// created at
	// Required: true
	// Format: date-time
	CreatedAt *strfmt.DateTime `json:"createdAt"`

	// deleted
	// Required: true
	Deleted *bool `json:"deleted"`

	// id
	// Required: true
	ID *IDRole `json:"id"`

	// modified at
	// Required: true
	// Format: date-time
	ModifiedAt *strfmt.DateTime `json:"modifiedAt"`

	// not deleted
	// Required: true
	NotDeleted *bool `json:"notDeleted"`

	// principal Id
	// Required: true
	PrincipalID *IDPrincipal `json:"principalId"`

	// raw external Id
	RawExternalID string `json:"rawExternalId,omitempty"`

	// resource Id
	// Required: true
	ResourceID *IDResource `json:"resourceId"`

	// roles
	// Required: true
	Roles []*IDRoleMeta `json:"roles"`

	// state
	// Required: true
	State *State `json:"state"`
}
