package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// RoleMeta RoleMeta
//
// swagger:model RoleMeta
type RoleMeta struct {

	// checked Id
	CheckedID int64 `json:"checkedId,omitempty"`

	// checked raw external Id
	CheckedRawExternalID string `json:"checkedRawExternalId,omitempty"`

	// content
	Content *JSONNode `json:"content,omitempty"`

	// id
	// Required: true
	ID *IDRoleMeta `json:"id"`

	// raw external Id
	RawExternalID string `json:"rawExternalId,omitempty"`
}
