package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Row Row
//
// swagger:model Row
type Row struct {

	// participant info
	ParticipantInfo *Participant `json:"participantInfo,omitempty"`

	// place from
	PlaceFrom int32 `json:"placeFrom,omitempty"`

	// place to
	PlaceTo int32 `json:"placeTo,omitempty"`

	// problem results
	ProblemResults []*ProblemResult `json:"problemResults"`

	// score
	Score string `json:"score,omitempty"`
}
