package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// RowTitle RowTitle
//
// swagger:model RowTitle
type RowTitle struct {

	// name
	Name string `json:"name,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}
