package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// RunReport RunReport
//
// swagger:model RunReport
type RunReport struct {

	// run Id
	RunID int64 `json:"runId,omitempty"`
}
