package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ServiceCapacity ServiceCapacity
//
// swagger:model ServiceCapacity
type ServiceCapacity struct {

	// submissions count
	// Required: true
	SubmissionsCount *int64 `json:"submissionsCount"`
}
