package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Statement Statement
//
// swagger:model Statement
type Statement struct {

	// path
	Path string `json:"path,omitempty"`

	// type
	// Enum: [TEX PDF BINARY OLYMP MARKDOWN]
	Type string `json:"type,omitempty"`
}
