package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Submission Submission
//
// swagger:model Submission
type Submission struct {

	// author
	// Required: true
	Author *string `json:"author"`

	// compiler
	// Required: true
	Compiler *string `json:"compiler"`

	// id
	// Required: true
	ID *int64 `json:"id"`

	// memory
	// Required: true
	Memory *int64 `json:"memory"`

	// problem alias
	// Required: true
	ProblemAlias *string `json:"problemAlias"`

	// problem Id
	// Required: true
	ProblemID *string `json:"problemId"`

	// test
	// Required: true
	Test *int32 `json:"test"`

	// time
	// Required: true
	Time *int64 `json:"time"`

	// verdict
	// Required: true
	Verdict *string `json:"verdict"`
}
