package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Submissions Submissions
//
// swagger:model Submissions
type Submissions struct {

	// submissions
	Submissions []*Submission `json:"submissions"`
}
