package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Team Team
//
// swagger:model Team
type Team struct {

	// id
	// Required: true
	ID *int64 `json:"id"`

	// invited
	Invited []*User `json:"invited"`

	// name
	Name string `json:"name,omitempty"`

	// teammates
	Teammates []*User `json:"teammates"`
}
