package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// TestLog TestLog
//
// swagger:model TestLog
type TestLog struct {

	// answer
	// Required: true
	Answer *string `json:"answer"`

	// checker error
	// Required: true
	CheckerError *string `json:"checkerError"`

	// error
	// Required: true
	Error *string `json:"error"`

	// input
	// Required: true
	Input *string `json:"input"`

	// is sample
	// Required: true
	IsSample *bool `json:"isSample"`

	// memory used
	// Required: true
	MemoryUsed *int64 `json:"memoryUsed"`

	// message
	// Required: true
	Message *string `json:"message"`

	// output
	// Required: true
	Output *string `json:"output"`

	// running time
	// Required: true
	RunningTime *int64 `json:"runningTime"`

	// sequence number
	// Required: true
	SequenceNumber *int32 `json:"sequenceNumber"`

	// test name
	// Required: true
	TestName *string `json:"testName"`

	// testset idx
	// Required: true
	TestsetIdx *int32 `json:"testsetIdx"`

	// verdict
	// Required: true
	Verdict *string `json:"verdict"`
}
