package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// UserGroup UserGroup
//
// swagger:model UserGroup
type UserGroup struct {

	// global
	Global bool `json:"global,omitempty"`

	// id
	// Required: true
	ID *int64 `json:"id"`

	// name
	Name string `json:"name,omitempty"`

	// owner
	Owner *User `json:"owner,omitempty"`

	// system
	System bool `json:"system,omitempty"`

	// user access
	UserAccess map[string]string `json:"userAccess,omitempty"`

	// users
	Users []*User `json:"users"`
}
