package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// UserWithPasswordResponse UserWithPasswordResponse
//
// swagger:model UserWithPasswordResponse
type UserWithPasswordResponse struct {

	// login
	// Required: true
	Login *string `json:"login"`

	// password
	// Required: true
	Password *string `json:"password"`

	// user Id
	// Required: true
	UserID *int64 `json:"userId"`
}
