// Code generated by go-swagger; DO NOT EDIT.

package api_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamdbnn/go-yandex-contest/models"
)

// GenerateInternalUserPasswordUsingPOSTReader is a Reader for the GenerateInternalUserPasswordUsingPOST structure.
type GenerateInternalUserPasswordUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GenerateInternalUserPasswordUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGenerateInternalUserPasswordUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGenerateInternalUserPasswordUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGenerateInternalUserPasswordUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGenerateInternalUserPasswordUsingPOSTOK creates a GenerateInternalUserPasswordUsingPOSTOK with default headers values
func NewGenerateInternalUserPasswordUsingPOSTOK() *GenerateInternalUserPasswordUsingPOSTOK {
	return &GenerateInternalUserPasswordUsingPOSTOK{}
}

/* GenerateInternalUserPasswordUsingPOSTOK describes a response with status code 200, with default header values.

Successfully generated internal user password
*/
type GenerateInternalUserPasswordUsingPOSTOK struct {
	Payload *models.UserWithPasswordResponse
}

func (o *GenerateInternalUserPasswordUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /user/{userId}/generate-password][%d] generateInternalUserPasswordUsingPOSTOK  %+v", 200, o.Payload)
}
func (o *GenerateInternalUserPasswordUsingPOSTOK) GetPayload() *models.UserWithPasswordResponse {
	return o.Payload
}

func (o *GenerateInternalUserPasswordUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserWithPasswordResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGenerateInternalUserPasswordUsingPOSTUnauthorized creates a GenerateInternalUserPasswordUsingPOSTUnauthorized with default headers values
func NewGenerateInternalUserPasswordUsingPOSTUnauthorized() *GenerateInternalUserPasswordUsingPOSTUnauthorized {
	return &GenerateInternalUserPasswordUsingPOSTUnauthorized{}
}

/* GenerateInternalUserPasswordUsingPOSTUnauthorized describes a response with status code 401, with default header values.

OAuth header is not declared or is wrong
*/
type GenerateInternalUserPasswordUsingPOSTUnauthorized struct {
}

func (o *GenerateInternalUserPasswordUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /user/{userId}/generate-password][%d] generateInternalUserPasswordUsingPOSTUnauthorized ", 401)
}

func (o *GenerateInternalUserPasswordUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGenerateInternalUserPasswordUsingPOSTForbidden creates a GenerateInternalUserPasswordUsingPOSTForbidden with default headers values
func NewGenerateInternalUserPasswordUsingPOSTForbidden() *GenerateInternalUserPasswordUsingPOSTForbidden {
	return &GenerateInternalUserPasswordUsingPOSTForbidden{}
}

/* GenerateInternalUserPasswordUsingPOSTForbidden describes a response with status code 403, with default header values.

You don't have enough permissions
*/
type GenerateInternalUserPasswordUsingPOSTForbidden struct {
}

func (o *GenerateInternalUserPasswordUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /user/{userId}/generate-password][%d] generateInternalUserPasswordUsingPOSTForbidden ", 403)
}

func (o *GenerateInternalUserPasswordUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
