// Code generated by go-swagger; DO NOT EDIT.

package api_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamdbnn/go-yandex-contest/models"
)

// GetYourStatusUsingGETReader is a Reader for the GetYourStatusUsingGET structure.
type GetYourStatusUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetYourStatusUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetYourStatusUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetYourStatusUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetYourStatusUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetYourStatusUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetYourStatusUsingGETOK creates a GetYourStatusUsingGETOK with default headers values
func NewGetYourStatusUsingGETOK() *GetYourStatusUsingGETOK {
	return &GetYourStatusUsingGETOK{}
}

/* GetYourStatusUsingGETOK describes a response with status code 200, with default header values.

Successfully received information about participant
*/
type GetYourStatusUsingGETOK struct {
	Payload *models.ParticipantStatus
}

func (o *GetYourStatusUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/participation][%d] getYourStatusUsingGETOK  %+v", 200, o.Payload)
}
func (o *GetYourStatusUsingGETOK) GetPayload() *models.ParticipantStatus {
	return o.Payload
}

func (o *GetYourStatusUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ParticipantStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetYourStatusUsingGETUnauthorized creates a GetYourStatusUsingGETUnauthorized with default headers values
func NewGetYourStatusUsingGETUnauthorized() *GetYourStatusUsingGETUnauthorized {
	return &GetYourStatusUsingGETUnauthorized{}
}

/* GetYourStatusUsingGETUnauthorized describes a response with status code 401, with default header values.

OAuth header is not declared or is wrong
*/
type GetYourStatusUsingGETUnauthorized struct {
}

func (o *GetYourStatusUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/participation][%d] getYourStatusUsingGETUnauthorized ", 401)
}

func (o *GetYourStatusUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetYourStatusUsingGETForbidden creates a GetYourStatusUsingGETForbidden with default headers values
func NewGetYourStatusUsingGETForbidden() *GetYourStatusUsingGETForbidden {
	return &GetYourStatusUsingGETForbidden{}
}

/* GetYourStatusUsingGETForbidden describes a response with status code 403, with default header values.

You don't have enough permissions
*/
type GetYourStatusUsingGETForbidden struct {
}

func (o *GetYourStatusUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/participation][%d] getYourStatusUsingGETForbidden ", 403)
}

func (o *GetYourStatusUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetYourStatusUsingGETNotFound creates a GetYourStatusUsingGETNotFound with default headers values
func NewGetYourStatusUsingGETNotFound() *GetYourStatusUsingGETNotFound {
	return &GetYourStatusUsingGETNotFound{}
}

/* GetYourStatusUsingGETNotFound describes a response with status code 404, with default header values.

User or contest not found
*/
type GetYourStatusUsingGETNotFound struct {
}

func (o *GetYourStatusUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/participation][%d] getYourStatusUsingGETNotFound ", 404)
}

func (o *GetYourStatusUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
