// Code generated by go-swagger; DO NOT EDIT.

package api_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetMessagesUsingGETParams creates a new GetMessagesUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMessagesUsingGETParams() *GetMessagesUsingGETParams {
	return &GetMessagesUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMessagesUsingGETParamsWithTimeout creates a new GetMessagesUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetMessagesUsingGETParamsWithTimeout(timeout time.Duration) *GetMessagesUsingGETParams {
	return &GetMessagesUsingGETParams{
		timeout: timeout,
	}
}

// NewGetMessagesUsingGETParamsWithContext creates a new GetMessagesUsingGETParams object
// with the ability to set a context for a request.
func NewGetMessagesUsingGETParamsWithContext(ctx context.Context) *GetMessagesUsingGETParams {
	return &GetMessagesUsingGETParams{
		Context: ctx,
	}
}

// NewGetMessagesUsingGETParamsWithHTTPClient creates a new GetMessagesUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMessagesUsingGETParamsWithHTTPClient(client *http.Client) *GetMessagesUsingGETParams {
	return &GetMessagesUsingGETParams{
		HTTPClient: client,
	}
}

/* GetMessagesUsingGETParams contains all the parameters to send to the API endpoint
   for the get messages using g e t operation.

   Typically these are written to a http.Request.
*/
type GetMessagesUsingGETParams struct {

	/* ContestID.

	   contestId

	   Format: int64
	*/
	ContestID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get messages using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMessagesUsingGETParams) WithDefaults() *GetMessagesUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get messages using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMessagesUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get messages using g e t params
func (o *GetMessagesUsingGETParams) WithTimeout(timeout time.Duration) *GetMessagesUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get messages using g e t params
func (o *GetMessagesUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get messages using g e t params
func (o *GetMessagesUsingGETParams) WithContext(ctx context.Context) *GetMessagesUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get messages using g e t params
func (o *GetMessagesUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get messages using g e t params
func (o *GetMessagesUsingGETParams) WithHTTPClient(client *http.Client) *GetMessagesUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get messages using g e t params
func (o *GetMessagesUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContestID adds the contestID to the get messages using g e t params
func (o *GetMessagesUsingGETParams) WithContestID(contestID int64) *GetMessagesUsingGETParams {
	o.SetContestID(contestID)
	return o
}

// SetContestID adds the contestId to the get messages using g e t params
func (o *GetMessagesUsingGETParams) SetContestID(contestID int64) {
	o.ContestID = contestID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMessagesUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contestId
	if err := r.SetPathParam("contestId", swag.FormatInt64(o.ContestID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
