// Code generated by go-swagger; DO NOT EDIT.

package api_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamdbnn/go-yandex-contest/models"
)

// GetParticipantStatusUsingGETReader is a Reader for the GetParticipantStatusUsingGET structure.
type GetParticipantStatusUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetParticipantStatusUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetParticipantStatusUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetParticipantStatusUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetParticipantStatusUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetParticipantStatusUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetParticipantStatusUsingGETOK creates a GetParticipantStatusUsingGETOK with default headers values
func NewGetParticipantStatusUsingGETOK() *GetParticipantStatusUsingGETOK {
	return &GetParticipantStatusUsingGETOK{}
}

/* GetParticipantStatusUsingGETOK describes a response with status code 200, with default header values.

Successfully received information about participant
*/
type GetParticipantStatusUsingGETOK struct {
	Payload *models.ParticipantStatus
}

func (o *GetParticipantStatusUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/participants/{participantId}][%d] getParticipantStatusUsingGETOK  %+v", 200, o.Payload)
}
func (o *GetParticipantStatusUsingGETOK) GetPayload() *models.ParticipantStatus {
	return o.Payload
}

func (o *GetParticipantStatusUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ParticipantStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetParticipantStatusUsingGETUnauthorized creates a GetParticipantStatusUsingGETUnauthorized with default headers values
func NewGetParticipantStatusUsingGETUnauthorized() *GetParticipantStatusUsingGETUnauthorized {
	return &GetParticipantStatusUsingGETUnauthorized{}
}

/* GetParticipantStatusUsingGETUnauthorized describes a response with status code 401, with default header values.

OAuth header is not declared or is wrong
*/
type GetParticipantStatusUsingGETUnauthorized struct {
}

func (o *GetParticipantStatusUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/participants/{participantId}][%d] getParticipantStatusUsingGETUnauthorized ", 401)
}

func (o *GetParticipantStatusUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetParticipantStatusUsingGETForbidden creates a GetParticipantStatusUsingGETForbidden with default headers values
func NewGetParticipantStatusUsingGETForbidden() *GetParticipantStatusUsingGETForbidden {
	return &GetParticipantStatusUsingGETForbidden{}
}

/* GetParticipantStatusUsingGETForbidden describes a response with status code 403, with default header values.

You don't have enough permissions
*/
type GetParticipantStatusUsingGETForbidden struct {
}

func (o *GetParticipantStatusUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/participants/{participantId}][%d] getParticipantStatusUsingGETForbidden ", 403)
}

func (o *GetParticipantStatusUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetParticipantStatusUsingGETNotFound creates a GetParticipantStatusUsingGETNotFound with default headers values
func NewGetParticipantStatusUsingGETNotFound() *GetParticipantStatusUsingGETNotFound {
	return &GetParticipantStatusUsingGETNotFound{}
}

/* GetParticipantStatusUsingGETNotFound describes a response with status code 404, with default header values.

User or contest not found
*/
type GetParticipantStatusUsingGETNotFound struct {
}

func (o *GetParticipantStatusUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/participants/{participantId}][%d] getParticipantStatusUsingGETNotFound ", 404)
}

func (o *GetParticipantStatusUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
