// Code generated by go-swagger; DO NOT EDIT.

package api_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDetailedReportUsingGETParams creates a new GetDetailedReportUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDetailedReportUsingGETParams() *GetDetailedReportUsingGETParams {
	return &GetDetailedReportUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDetailedReportUsingGETParamsWithTimeout creates a new GetDetailedReportUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetDetailedReportUsingGETParamsWithTimeout(timeout time.Duration) *GetDetailedReportUsingGETParams {
	return &GetDetailedReportUsingGETParams{
		timeout: timeout,
	}
}

// NewGetDetailedReportUsingGETParamsWithContext creates a new GetDetailedReportUsingGETParams object
// with the ability to set a context for a request.
func NewGetDetailedReportUsingGETParamsWithContext(ctx context.Context) *GetDetailedReportUsingGETParams {
	return &GetDetailedReportUsingGETParams{
		Context: ctx,
	}
}

// NewGetDetailedReportUsingGETParamsWithHTTPClient creates a new GetDetailedReportUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDetailedReportUsingGETParamsWithHTTPClient(client *http.Client) *GetDetailedReportUsingGETParams {
	return &GetDetailedReportUsingGETParams{
		HTTPClient: client,
	}
}

/* GetDetailedReportUsingGETParams contains all the parameters to send to the API endpoint
   for the get detailed report using g e t operation.

   Typically these are written to a http.Request.
*/
type GetDetailedReportUsingGETParams struct {

	/* ContestID.

	   contestId

	   Format: int64
	*/
	ContestID int64

	/* RunID.

	   runId

	   Format: int64
	*/
	RunID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get detailed report using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDetailedReportUsingGETParams) WithDefaults() *GetDetailedReportUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get detailed report using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDetailedReportUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get detailed report using g e t params
func (o *GetDetailedReportUsingGETParams) WithTimeout(timeout time.Duration) *GetDetailedReportUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get detailed report using g e t params
func (o *GetDetailedReportUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get detailed report using g e t params
func (o *GetDetailedReportUsingGETParams) WithContext(ctx context.Context) *GetDetailedReportUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get detailed report using g e t params
func (o *GetDetailedReportUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get detailed report using g e t params
func (o *GetDetailedReportUsingGETParams) WithHTTPClient(client *http.Client) *GetDetailedReportUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get detailed report using g e t params
func (o *GetDetailedReportUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContestID adds the contestID to the get detailed report using g e t params
func (o *GetDetailedReportUsingGETParams) WithContestID(contestID int64) *GetDetailedReportUsingGETParams {
	o.SetContestID(contestID)
	return o
}

// SetContestID adds the contestId to the get detailed report using g e t params
func (o *GetDetailedReportUsingGETParams) SetContestID(contestID int64) {
	o.ContestID = contestID
}

// WithRunID adds the runID to the get detailed report using g e t params
func (o *GetDetailedReportUsingGETParams) WithRunID(runID int64) *GetDetailedReportUsingGETParams {
	o.SetRunID(runID)
	return o
}

// SetRunID adds the runId to the get detailed report using g e t params
func (o *GetDetailedReportUsingGETParams) SetRunID(runID int64) {
	o.RunID = runID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDetailedReportUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contestId
	if err := r.SetPathParam("contestId", swag.FormatInt64(o.ContestID)); err != nil {
		return err
	}

	// path param runId
	if err := r.SetPathParam("runId", swag.FormatInt64(o.RunID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
