// Code generated by go-swagger; DO NOT EDIT.

package api_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamdbnn/go-yandex-contest/models"
)

// GetMessagesUsingGETReader is a Reader for the GetMessagesUsingGET structure.
type GetMessagesUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMessagesUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMessagesUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetMessagesUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetMessagesUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetMessagesUsingGETOK creates a GetMessagesUsingGETOK with default headers values
func NewGetMessagesUsingGETOK() *GetMessagesUsingGETOK {
	return &GetMessagesUsingGETOK{}
}

/* GetMessagesUsingGETOK describes a response with status code 200, with default header values.

Successfully received messages
*/
type GetMessagesUsingGETOK struct {
	Payload *models.Messages
}

func (o *GetMessagesUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/messages][%d] getMessagesUsingGETOK  %+v", 200, o.Payload)
}
func (o *GetMessagesUsingGETOK) GetPayload() *models.Messages {
	return o.Payload
}

func (o *GetMessagesUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Messages)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMessagesUsingGETUnauthorized creates a GetMessagesUsingGETUnauthorized with default headers values
func NewGetMessagesUsingGETUnauthorized() *GetMessagesUsingGETUnauthorized {
	return &GetMessagesUsingGETUnauthorized{}
}

/* GetMessagesUsingGETUnauthorized describes a response with status code 401, with default header values.

OAuth header is not declared or is wrong
*/
type GetMessagesUsingGETUnauthorized struct {
}

func (o *GetMessagesUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/messages][%d] getMessagesUsingGETUnauthorized ", 401)
}

func (o *GetMessagesUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetMessagesUsingGETNotFound creates a GetMessagesUsingGETNotFound with default headers values
func NewGetMessagesUsingGETNotFound() *GetMessagesUsingGETNotFound {
	return &GetMessagesUsingGETNotFound{}
}

/* GetMessagesUsingGETNotFound describes a response with status code 404, with default header values.

Contest not found
*/
type GetMessagesUsingGETNotFound struct {
}

func (o *GetMessagesUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/messages][%d] getMessagesUsingGETNotFound ", 404)
}

func (o *GetMessagesUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
