// Code generated by go-swagger; DO NOT EDIT.

package api_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetParticipantStatsUsingGETParams creates a new GetParticipantStatsUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetParticipantStatsUsingGETParams() *GetParticipantStatsUsingGETParams {
	return &GetParticipantStatsUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetParticipantStatsUsingGETParamsWithTimeout creates a new GetParticipantStatsUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetParticipantStatsUsingGETParamsWithTimeout(timeout time.Duration) *GetParticipantStatsUsingGETParams {
	return &GetParticipantStatsUsingGETParams{
		timeout: timeout,
	}
}

// NewGetParticipantStatsUsingGETParamsWithContext creates a new GetParticipantStatsUsingGETParams object
// with the ability to set a context for a request.
func NewGetParticipantStatsUsingGETParamsWithContext(ctx context.Context) *GetParticipantStatsUsingGETParams {
	return &GetParticipantStatsUsingGETParams{
		Context: ctx,
	}
}

// NewGetParticipantStatsUsingGETParamsWithHTTPClient creates a new GetParticipantStatsUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetParticipantStatsUsingGETParamsWithHTTPClient(client *http.Client) *GetParticipantStatsUsingGETParams {
	return &GetParticipantStatsUsingGETParams{
		HTTPClient: client,
	}
}

/* GetParticipantStatsUsingGETParams contains all the parameters to send to the API endpoint
   for the get participant stats using g e t operation.

   Typically these are written to a http.Request.
*/
type GetParticipantStatsUsingGETParams struct {

	/* ContestID.

	   contestId

	   Format: int64
	*/
	ContestID int64

	/* ParticipantID.

	   participantId

	   Format: int64
	*/
	ParticipantID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get participant stats using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetParticipantStatsUsingGETParams) WithDefaults() *GetParticipantStatsUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get participant stats using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetParticipantStatsUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get participant stats using g e t params
func (o *GetParticipantStatsUsingGETParams) WithTimeout(timeout time.Duration) *GetParticipantStatsUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get participant stats using g e t params
func (o *GetParticipantStatsUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get participant stats using g e t params
func (o *GetParticipantStatsUsingGETParams) WithContext(ctx context.Context) *GetParticipantStatsUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get participant stats using g e t params
func (o *GetParticipantStatsUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get participant stats using g e t params
func (o *GetParticipantStatsUsingGETParams) WithHTTPClient(client *http.Client) *GetParticipantStatsUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get participant stats using g e t params
func (o *GetParticipantStatsUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContestID adds the contestID to the get participant stats using g e t params
func (o *GetParticipantStatsUsingGETParams) WithContestID(contestID int64) *GetParticipantStatsUsingGETParams {
	o.SetContestID(contestID)
	return o
}

// SetContestID adds the contestId to the get participant stats using g e t params
func (o *GetParticipantStatsUsingGETParams) SetContestID(contestID int64) {
	o.ContestID = contestID
}

// WithParticipantID adds the participantID to the get participant stats using g e t params
func (o *GetParticipantStatsUsingGETParams) WithParticipantID(participantID int64) *GetParticipantStatsUsingGETParams {
	o.SetParticipantID(participantID)
	return o
}

// SetParticipantID adds the participantId to the get participant stats using g e t params
func (o *GetParticipantStatsUsingGETParams) SetParticipantID(participantID int64) {
	o.ParticipantID = participantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetParticipantStatsUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contestId
	if err := r.SetPathParam("contestId", swag.FormatInt64(o.ContestID)); err != nil {
		return err
	}

	// path param participantId
	if err := r.SetPathParam("participantId", swag.FormatInt64(o.ParticipantID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
