// Code generated by go-swagger; DO NOT EDIT.

package api_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetClarificationsUsingGETParams creates a new GetClarificationsUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetClarificationsUsingGETParams() *GetClarificationsUsingGETParams {
	return &GetClarificationsUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetClarificationsUsingGETParamsWithTimeout creates a new GetClarificationsUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetClarificationsUsingGETParamsWithTimeout(timeout time.Duration) *GetClarificationsUsingGETParams {
	return &GetClarificationsUsingGETParams{
		timeout: timeout,
	}
}

// NewGetClarificationsUsingGETParamsWithContext creates a new GetClarificationsUsingGETParams object
// with the ability to set a context for a request.
func NewGetClarificationsUsingGETParamsWithContext(ctx context.Context) *GetClarificationsUsingGETParams {
	return &GetClarificationsUsingGETParams{
		Context: ctx,
	}
}

// NewGetClarificationsUsingGETParamsWithHTTPClient creates a new GetClarificationsUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetClarificationsUsingGETParamsWithHTTPClient(client *http.Client) *GetClarificationsUsingGETParams {
	return &GetClarificationsUsingGETParams{
		HTTPClient: client,
	}
}

/* GetClarificationsUsingGETParams contains all the parameters to send to the API endpoint
   for the get clarifications using g e t operation.

   Typically these are written to a http.Request.
*/
type GetClarificationsUsingGETParams struct {

	/* ContestID.

	   contestId

	   Format: int64
	*/
	ContestID int64

	/* Locale.

	   locale

	   Default: "ru"
	*/
	Locale *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get clarifications using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClarificationsUsingGETParams) WithDefaults() *GetClarificationsUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get clarifications using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClarificationsUsingGETParams) SetDefaults() {
	var (
		localeDefault = string("ru")
	)

	val := GetClarificationsUsingGETParams{
		Locale: &localeDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get clarifications using g e t params
func (o *GetClarificationsUsingGETParams) WithTimeout(timeout time.Duration) *GetClarificationsUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get clarifications using g e t params
func (o *GetClarificationsUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get clarifications using g e t params
func (o *GetClarificationsUsingGETParams) WithContext(ctx context.Context) *GetClarificationsUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get clarifications using g e t params
func (o *GetClarificationsUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get clarifications using g e t params
func (o *GetClarificationsUsingGETParams) WithHTTPClient(client *http.Client) *GetClarificationsUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get clarifications using g e t params
func (o *GetClarificationsUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContestID adds the contestID to the get clarifications using g e t params
func (o *GetClarificationsUsingGETParams) WithContestID(contestID int64) *GetClarificationsUsingGETParams {
	o.SetContestID(contestID)
	return o
}

// SetContestID adds the contestId to the get clarifications using g e t params
func (o *GetClarificationsUsingGETParams) SetContestID(contestID int64) {
	o.ContestID = contestID
}

// WithLocale adds the locale to the get clarifications using g e t params
func (o *GetClarificationsUsingGETParams) WithLocale(locale *string) *GetClarificationsUsingGETParams {
	o.SetLocale(locale)
	return o
}

// SetLocale adds the locale to the get clarifications using g e t params
func (o *GetClarificationsUsingGETParams) SetLocale(locale *string) {
	o.Locale = locale
}

// WriteToRequest writes these params to a swagger request
func (o *GetClarificationsUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contestId
	if err := r.SetPathParam("contestId", swag.FormatInt64(o.ContestID)); err != nil {
		return err
	}

	if o.Locale != nil {

		// query param locale
		var qrLocale string

		if o.Locale != nil {
			qrLocale = *o.Locale
		}
		qLocale := qrLocale
		if qLocale != "" {

			if err := r.SetQueryParam("locale", qLocale); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
