// Code generated by go-swagger; DO NOT EDIT.

package api_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetParticipantsUsingGETParams creates a new GetParticipantsUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetParticipantsUsingGETParams() *GetParticipantsUsingGETParams {
	return &GetParticipantsUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetParticipantsUsingGETParamsWithTimeout creates a new GetParticipantsUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetParticipantsUsingGETParamsWithTimeout(timeout time.Duration) *GetParticipantsUsingGETParams {
	return &GetParticipantsUsingGETParams{
		timeout: timeout,
	}
}

// NewGetParticipantsUsingGETParamsWithContext creates a new GetParticipantsUsingGETParams object
// with the ability to set a context for a request.
func NewGetParticipantsUsingGETParamsWithContext(ctx context.Context) *GetParticipantsUsingGETParams {
	return &GetParticipantsUsingGETParams{
		Context: ctx,
	}
}

// NewGetParticipantsUsingGETParamsWithHTTPClient creates a new GetParticipantsUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetParticipantsUsingGETParamsWithHTTPClient(client *http.Client) *GetParticipantsUsingGETParams {
	return &GetParticipantsUsingGETParams{
		HTTPClient: client,
	}
}

/* GetParticipantsUsingGETParams contains all the parameters to send to the API endpoint
   for the get participants using g e t operation.

   Typically these are written to a http.Request.
*/
type GetParticipantsUsingGETParams struct {

	/* ContestID.

	   contestId

	   Format: int64
	*/
	ContestID int64

	/* DisplayName.

	   display_name
	*/
	DisplayName *string

	/* Login.

	   login
	*/
	Login *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get participants using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetParticipantsUsingGETParams) WithDefaults() *GetParticipantsUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get participants using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetParticipantsUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get participants using g e t params
func (o *GetParticipantsUsingGETParams) WithTimeout(timeout time.Duration) *GetParticipantsUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get participants using g e t params
func (o *GetParticipantsUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get participants using g e t params
func (o *GetParticipantsUsingGETParams) WithContext(ctx context.Context) *GetParticipantsUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get participants using g e t params
func (o *GetParticipantsUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get participants using g e t params
func (o *GetParticipantsUsingGETParams) WithHTTPClient(client *http.Client) *GetParticipantsUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get participants using g e t params
func (o *GetParticipantsUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContestID adds the contestID to the get participants using g e t params
func (o *GetParticipantsUsingGETParams) WithContestID(contestID int64) *GetParticipantsUsingGETParams {
	o.SetContestID(contestID)
	return o
}

// SetContestID adds the contestId to the get participants using g e t params
func (o *GetParticipantsUsingGETParams) SetContestID(contestID int64) {
	o.ContestID = contestID
}

// WithDisplayName adds the displayName to the get participants using g e t params
func (o *GetParticipantsUsingGETParams) WithDisplayName(displayName *string) *GetParticipantsUsingGETParams {
	o.SetDisplayName(displayName)
	return o
}

// SetDisplayName adds the displayName to the get participants using g e t params
func (o *GetParticipantsUsingGETParams) SetDisplayName(displayName *string) {
	o.DisplayName = displayName
}

// WithLogin adds the login to the get participants using g e t params
func (o *GetParticipantsUsingGETParams) WithLogin(login *string) *GetParticipantsUsingGETParams {
	o.SetLogin(login)
	return o
}

// SetLogin adds the login to the get participants using g e t params
func (o *GetParticipantsUsingGETParams) SetLogin(login *string) {
	o.Login = login
}

// WriteToRequest writes these params to a swagger request
func (o *GetParticipantsUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contestId
	if err := r.SetPathParam("contestId", swag.FormatInt64(o.ContestID)); err != nil {
		return err
	}

	if o.DisplayName != nil {

		// query param display_name
		var qrDisplayName string

		if o.DisplayName != nil {
			qrDisplayName = *o.DisplayName
		}
		qDisplayName := qrDisplayName
		if qDisplayName != "" {

			if err := r.SetQueryParam("display_name", qDisplayName); err != nil {
				return err
			}
		}
	}

	if o.Login != nil {

		// query param login
		var qrLogin string

		if o.Login != nil {
			qrLogin = *o.Login
		}
		qLogin := qrLogin
		if qLogin != "" {

			if err := r.SetQueryParam("login", qLogin); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
