// Code generated by go-swagger; DO NOT EDIT.

package api_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetSourceCodeUsingGETParams creates a new GetSourceCodeUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSourceCodeUsingGETParams() *GetSourceCodeUsingGETParams {
	return &GetSourceCodeUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSourceCodeUsingGETParamsWithTimeout creates a new GetSourceCodeUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetSourceCodeUsingGETParamsWithTimeout(timeout time.Duration) *GetSourceCodeUsingGETParams {
	return &GetSourceCodeUsingGETParams{
		timeout: timeout,
	}
}

// NewGetSourceCodeUsingGETParamsWithContext creates a new GetSourceCodeUsingGETParams object
// with the ability to set a context for a request.
func NewGetSourceCodeUsingGETParamsWithContext(ctx context.Context) *GetSourceCodeUsingGETParams {
	return &GetSourceCodeUsingGETParams{
		Context: ctx,
	}
}

// NewGetSourceCodeUsingGETParamsWithHTTPClient creates a new GetSourceCodeUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSourceCodeUsingGETParamsWithHTTPClient(client *http.Client) *GetSourceCodeUsingGETParams {
	return &GetSourceCodeUsingGETParams{
		HTTPClient: client,
	}
}

/* GetSourceCodeUsingGETParams contains all the parameters to send to the API endpoint
   for the get source code using g e t operation.

   Typically these are written to a http.Request.
*/
type GetSourceCodeUsingGETParams struct {

	/* ContestID.

	   contestId

	   Format: int64
	*/
	ContestID int64

	/* RunID.

	   runId

	   Format: int64
	*/
	RunID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get source code using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSourceCodeUsingGETParams) WithDefaults() *GetSourceCodeUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get source code using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSourceCodeUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get source code using g e t params
func (o *GetSourceCodeUsingGETParams) WithTimeout(timeout time.Duration) *GetSourceCodeUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get source code using g e t params
func (o *GetSourceCodeUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get source code using g e t params
func (o *GetSourceCodeUsingGETParams) WithContext(ctx context.Context) *GetSourceCodeUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get source code using g e t params
func (o *GetSourceCodeUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get source code using g e t params
func (o *GetSourceCodeUsingGETParams) WithHTTPClient(client *http.Client) *GetSourceCodeUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get source code using g e t params
func (o *GetSourceCodeUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContestID adds the contestID to the get source code using g e t params
func (o *GetSourceCodeUsingGETParams) WithContestID(contestID int64) *GetSourceCodeUsingGETParams {
	o.SetContestID(contestID)
	return o
}

// SetContestID adds the contestId to the get source code using g e t params
func (o *GetSourceCodeUsingGETParams) SetContestID(contestID int64) {
	o.ContestID = contestID
}

// WithRunID adds the runID to the get source code using g e t params
func (o *GetSourceCodeUsingGETParams) WithRunID(runID int64) *GetSourceCodeUsingGETParams {
	o.SetRunID(runID)
	return o
}

// SetRunID adds the runId to the get source code using g e t params
func (o *GetSourceCodeUsingGETParams) SetRunID(runID int64) {
	o.RunID = runID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSourceCodeUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contestId
	if err := r.SetPathParam("contestId", swag.FormatInt64(o.ContestID)); err != nil {
		return err
	}

	// path param runId
	if err := r.SetPathParam("runId", swag.FormatInt64(o.RunID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
