// Code generated by go-swagger; DO NOT EDIT.

package api_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamdbnn/go-yandex-contest/models"
)

// GetParticipantsUsingGETReader is a Reader for the GetParticipantsUsingGET structure.
type GetParticipantsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetParticipantsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetParticipantsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetParticipantsUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetParticipantsUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetParticipantsUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetParticipantsUsingGETOK creates a GetParticipantsUsingGETOK with default headers values
func NewGetParticipantsUsingGETOK() *GetParticipantsUsingGETOK {
	return &GetParticipantsUsingGETOK{}
}

/* GetParticipantsUsingGETOK describes a response with status code 200, with default header values.

Successfully received information about contest participants
*/
type GetParticipantsUsingGETOK struct {
	Payload []*models.Participant
}

func (o *GetParticipantsUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/participants][%d] getParticipantsUsingGETOK  %+v", 200, o.Payload)
}
func (o *GetParticipantsUsingGETOK) GetPayload() []*models.Participant {
	return o.Payload
}

func (o *GetParticipantsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetParticipantsUsingGETUnauthorized creates a GetParticipantsUsingGETUnauthorized with default headers values
func NewGetParticipantsUsingGETUnauthorized() *GetParticipantsUsingGETUnauthorized {
	return &GetParticipantsUsingGETUnauthorized{}
}

/* GetParticipantsUsingGETUnauthorized describes a response with status code 401, with default header values.

OAuth header is not declared or is wrong
*/
type GetParticipantsUsingGETUnauthorized struct {
}

func (o *GetParticipantsUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/participants][%d] getParticipantsUsingGETUnauthorized ", 401)
}

func (o *GetParticipantsUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetParticipantsUsingGETForbidden creates a GetParticipantsUsingGETForbidden with default headers values
func NewGetParticipantsUsingGETForbidden() *GetParticipantsUsingGETForbidden {
	return &GetParticipantsUsingGETForbidden{}
}

/* GetParticipantsUsingGETForbidden describes a response with status code 403, with default header values.

You don't have enough permissions
*/
type GetParticipantsUsingGETForbidden struct {
}

func (o *GetParticipantsUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/participants][%d] getParticipantsUsingGETForbidden ", 403)
}

func (o *GetParticipantsUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetParticipantsUsingGETNotFound creates a GetParticipantsUsingGETNotFound with default headers values
func NewGetParticipantsUsingGETNotFound() *GetParticipantsUsingGETNotFound {
	return &GetParticipantsUsingGETNotFound{}
}

/* GetParticipantsUsingGETNotFound describes a response with status code 404, with default header values.

Contest not found
*/
type GetParticipantsUsingGETNotFound struct {
}

func (o *GetParticipantsUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/participants][%d] getParticipantsUsingGETNotFound ", 404)
}

func (o *GetParticipantsUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
