// Code generated by go-swagger; DO NOT EDIT.

package api_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/teamdbnn/go-yandex-contest/models"
)

// GetContestStandingsUsingGETReader is a Reader for the GetContestStandingsUsingGET structure.
type GetContestStandingsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetContestStandingsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetContestStandingsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetContestStandingsUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetContestStandingsUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetContestStandingsUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetContestStandingsUsingGETOK creates a GetContestStandingsUsingGETOK with default headers values
func NewGetContestStandingsUsingGETOK() *GetContestStandingsUsingGETOK {
	return &GetContestStandingsUsingGETOK{}
}

/* GetContestStandingsUsingGETOK describes a response with status code 200, with default header values.

Successfully received contest's standings
*/
type GetContestStandingsUsingGETOK struct {
	Payload *models.ContestStandings
}

func (o *GetContestStandingsUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/standings][%d] getContestStandingsUsingGETOK  %+v", 200, o.Payload)
}
func (o *GetContestStandingsUsingGETOK) GetPayload() *models.ContestStandings {
	return o.Payload
}

func (o *GetContestStandingsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContestStandings)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetContestStandingsUsingGETUnauthorized creates a GetContestStandingsUsingGETUnauthorized with default headers values
func NewGetContestStandingsUsingGETUnauthorized() *GetContestStandingsUsingGETUnauthorized {
	return &GetContestStandingsUsingGETUnauthorized{}
}

/* GetContestStandingsUsingGETUnauthorized describes a response with status code 401, with default header values.

OAuth header is not declared or is wrong
*/
type GetContestStandingsUsingGETUnauthorized struct {
}

func (o *GetContestStandingsUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/standings][%d] getContestStandingsUsingGETUnauthorized ", 401)
}

func (o *GetContestStandingsUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetContestStandingsUsingGETForbidden creates a GetContestStandingsUsingGETForbidden with default headers values
func NewGetContestStandingsUsingGETForbidden() *GetContestStandingsUsingGETForbidden {
	return &GetContestStandingsUsingGETForbidden{}
}

/* GetContestStandingsUsingGETForbidden describes a response with status code 403, with default header values.

You have no access to this contest
*/
type GetContestStandingsUsingGETForbidden struct {
}

func (o *GetContestStandingsUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/standings][%d] getContestStandingsUsingGETForbidden ", 403)
}

func (o *GetContestStandingsUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetContestStandingsUsingGETNotFound creates a GetContestStandingsUsingGETNotFound with default headers values
func NewGetContestStandingsUsingGETNotFound() *GetContestStandingsUsingGETNotFound {
	return &GetContestStandingsUsingGETNotFound{}
}

/* GetContestStandingsUsingGETNotFound describes a response with status code 404, with default header values.

Contest not found
*/
type GetContestStandingsUsingGETNotFound struct {
}

func (o *GetContestStandingsUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /contests/{contestId}/standings][%d] getContestStandingsUsingGETNotFound ", 404)
}

func (o *GetContestStandingsUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
