// Code generated by go-swagger; DO NOT EDIT.

package api_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetMyStandingsUsingGETParams creates a new GetMyStandingsUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMyStandingsUsingGETParams() *GetMyStandingsUsingGETParams {
	return &GetMyStandingsUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMyStandingsUsingGETParamsWithTimeout creates a new GetMyStandingsUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetMyStandingsUsingGETParamsWithTimeout(timeout time.Duration) *GetMyStandingsUsingGETParams {
	return &GetMyStandingsUsingGETParams{
		timeout: timeout,
	}
}

// NewGetMyStandingsUsingGETParamsWithContext creates a new GetMyStandingsUsingGETParams object
// with the ability to set a context for a request.
func NewGetMyStandingsUsingGETParamsWithContext(ctx context.Context) *GetMyStandingsUsingGETParams {
	return &GetMyStandingsUsingGETParams{
		Context: ctx,
	}
}

// NewGetMyStandingsUsingGETParamsWithHTTPClient creates a new GetMyStandingsUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMyStandingsUsingGETParamsWithHTTPClient(client *http.Client) *GetMyStandingsUsingGETParams {
	return &GetMyStandingsUsingGETParams{
		HTTPClient: client,
	}
}

/* GetMyStandingsUsingGETParams contains all the parameters to send to the API endpoint
   for the get my standings using g e t operation.

   Typically these are written to a http.Request.
*/
type GetMyStandingsUsingGETParams struct {

	/* ContestID.

	   contestId

	   Format: int64
	*/
	ContestID int64

	/* ForJudge.

	   forJudge

	   Default: "false"
	*/
	ForJudge *string

	/* Locale.

	   locale

	   Default: "ru"
	*/
	Locale *string

	/* ShowExternal.

	   showExternal

	   Default: "false"
	*/
	ShowExternal *string

	/* ShowVirtual.

	   showVirtual

	   Default: "false"
	*/
	ShowVirtual *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get my standings using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMyStandingsUsingGETParams) WithDefaults() *GetMyStandingsUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get my standings using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMyStandingsUsingGETParams) SetDefaults() {
	var (
		forJudgeDefault = string("false")

		localeDefault = string("ru")

		showExternalDefault = string("false")

		showVirtualDefault = string("false")
	)

	val := GetMyStandingsUsingGETParams{
		ForJudge:     &forJudgeDefault,
		Locale:       &localeDefault,
		ShowExternal: &showExternalDefault,
		ShowVirtual:  &showVirtualDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) WithTimeout(timeout time.Duration) *GetMyStandingsUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) WithContext(ctx context.Context) *GetMyStandingsUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) WithHTTPClient(client *http.Client) *GetMyStandingsUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContestID adds the contestID to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) WithContestID(contestID int64) *GetMyStandingsUsingGETParams {
	o.SetContestID(contestID)
	return o
}

// SetContestID adds the contestId to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) SetContestID(contestID int64) {
	o.ContestID = contestID
}

// WithForJudge adds the forJudge to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) WithForJudge(forJudge *string) *GetMyStandingsUsingGETParams {
	o.SetForJudge(forJudge)
	return o
}

// SetForJudge adds the forJudge to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) SetForJudge(forJudge *string) {
	o.ForJudge = forJudge
}

// WithLocale adds the locale to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) WithLocale(locale *string) *GetMyStandingsUsingGETParams {
	o.SetLocale(locale)
	return o
}

// SetLocale adds the locale to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) SetLocale(locale *string) {
	o.Locale = locale
}

// WithShowExternal adds the showExternal to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) WithShowExternal(showExternal *string) *GetMyStandingsUsingGETParams {
	o.SetShowExternal(showExternal)
	return o
}

// SetShowExternal adds the showExternal to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) SetShowExternal(showExternal *string) {
	o.ShowExternal = showExternal
}

// WithShowVirtual adds the showVirtual to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) WithShowVirtual(showVirtual *string) *GetMyStandingsUsingGETParams {
	o.SetShowVirtual(showVirtual)
	return o
}

// SetShowVirtual adds the showVirtual to the get my standings using g e t params
func (o *GetMyStandingsUsingGETParams) SetShowVirtual(showVirtual *string) {
	o.ShowVirtual = showVirtual
}

// WriteToRequest writes these params to a swagger request
func (o *GetMyStandingsUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contestId
	if err := r.SetPathParam("contestId", swag.FormatInt64(o.ContestID)); err != nil {
		return err
	}

	if o.ForJudge != nil {

		// query param forJudge
		var qrForJudge string

		if o.ForJudge != nil {
			qrForJudge = *o.ForJudge
		}
		qForJudge := qrForJudge
		if qForJudge != "" {

			if err := r.SetQueryParam("forJudge", qForJudge); err != nil {
				return err
			}
		}
	}

	if o.Locale != nil {

		// query param locale
		var qrLocale string

		if o.Locale != nil {
			qrLocale = *o.Locale
		}
		qLocale := qrLocale
		if qLocale != "" {

			if err := r.SetQueryParam("locale", qLocale); err != nil {
				return err
			}
		}
	}

	if o.ShowExternal != nil {

		// query param showExternal
		var qrShowExternal string

		if o.ShowExternal != nil {
			qrShowExternal = *o.ShowExternal
		}
		qShowExternal := qrShowExternal
		if qShowExternal != "" {

			if err := r.SetQueryParam("showExternal", qShowExternal); err != nil {
				return err
			}
		}
	}

	if o.ShowVirtual != nil {

		// query param showVirtual
		var qrShowVirtual string

		if o.ShowVirtual != nil {
			qrShowVirtual = *o.ShowVirtual
		}
		qShowVirtual := qrShowVirtual
		if qShowVirtual != "" {

			if err := r.SetQueryParam("showVirtual", qShowVirtual); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
