// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Clarification Clarification
//
// swagger:model Clarification
type Clarification struct {

	// message
	Message string `json:"message,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`
}

// Validate validates this clarification
func (m *Clarification) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this clarification based on context it is used
func (m *Clarification) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Clarification) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Clarification) UnmarshalBinary(b []byte) error {
	var res Clarification
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
