// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Clarifications Clarifications
//
// swagger:model Clarifications
type Clarifications struct {

	// clarifications
	Clarifications []*Clarification `json:"clarifications"`
}

// Validate validates this clarifications
func (m *Clarifications) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClarifications(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Clarifications) validateClarifications(formats strfmt.Registry) error {
	if swag.IsZero(m.Clarifications) { // not required
		return nil
	}

	for i := 0; i < len(m.Clarifications); i++ {
		if swag.IsZero(m.Clarifications[i]) { // not required
			continue
		}

		if m.Clarifications[i] != nil {
			if err := m.Clarifications[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("clarifications" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this clarifications based on the context it is used
func (m *Clarifications) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateClarifications(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Clarifications) contextValidateClarifications(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Clarifications); i++ {

		if m.Clarifications[i] != nil {
			if err := m.Clarifications[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("clarifications" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Clarifications) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Clarifications) UnmarshalBinary(b []byte) error {
	var res Clarifications
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
