// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ContestDescription ContestDescription
//
// swagger:model ContestDescription
type ContestDescription struct {

	// duration
	Duration int64 `json:"duration,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// start time
	StartTime string `json:"startTime,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this contest description
func (m *ContestDescription) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this contest description based on context it is used
func (m *ContestDescription) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ContestDescription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContestDescription) UnmarshalBinary(b []byte) error {
	var res ContestDescription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
