// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DirectoryPackage DirectoryPackage
//
// swagger:model DirectoryPackage
type DirectoryPackage struct {
	nameField string

	DirectoryPackageAllOf1
}

// Name gets the name of this subtype
func (m *DirectoryPackage) Name() string {
	return m.nameField
}

// SetName sets the name of this subtype
func (m *DirectoryPackage) SetName(val string) {
	m.nameField = val
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *DirectoryPackage) UnmarshalJSON(raw []byte) error {
	var data struct {
		DirectoryPackageAllOf1
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		Name string `json:"name,omitempty"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result DirectoryPackage

	result.nameField = base.Name

	result.DirectoryPackageAllOf1 = data.DirectoryPackageAllOf1

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m DirectoryPackage) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {
		DirectoryPackageAllOf1
	}{

		DirectoryPackageAllOf1: m.DirectoryPackageAllOf1,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		Name string `json:"name,omitempty"`
	}{

		Name: m.Name(),
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this directory package
func (m *DirectoryPackage) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with DirectoryPackageAllOf1
	if err := m.DirectoryPackageAllOf1.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this directory package based on the context it is used
func (m *DirectoryPackage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with DirectoryPackageAllOf1
	if err := m.DirectoryPackageAllOf1.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DirectoryPackage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DirectoryPackage) UnmarshalBinary(b []byte) error {
	var res DirectoryPackage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
