// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExternalID ExternalId
//
// swagger:model ExternalId
type ExternalID struct {

	// client Id
	// Required: true
	ClientID *string `json:"clientId"`

	// empty
	// Required: true
	Empty *bool `json:"empty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this external Id
func (m *ExternalID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEmpty(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExternalID) validateClientID(formats strfmt.Registry) error {

	if err := validate.Required("clientId", "body", m.ClientID); err != nil {
		return err
	}

	return nil
}

func (m *ExternalID) validateEmpty(formats strfmt.Registry) error {

	if err := validate.Required("empty", "body", m.Empty); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this external Id based on context it is used
func (m *ExternalID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExternalID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExternalID) UnmarshalBinary(b []byte) error {
	var res ExternalID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
