// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FilePackageAllOf1 FilePackage
//
// swagger:model filePackageAllOf1
type FilePackageAllOf1 struct {

	// data
	// Format: binary
	Data io.ReadCloser `json:"data,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this file package all of1
func (m *FilePackageAllOf1) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this file package all of1 based on context it is used
func (m *FilePackageAllOf1) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FilePackageAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FilePackageAllOf1) UnmarshalBinary(b []byte) error {
	var res FilePackageAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
