// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FullRunReport FullRunReport
//
// swagger:model FullRunReport
type FullRunReport struct {

	// checker log
	// Required: true
	CheckerLog []*TestLog `json:"checkerLog"`

	// compile log
	// Required: true
	CompileLog *string `json:"compileLog"`

	// compiler
	// Required: true
	Compiler *string `json:"compiler"`

	// contest Id
	// Required: true
	ContestID *int64 `json:"contestId"`

	// contest name
	// Required: true
	ContestName *string `json:"contestName"`

	// diff
	// Required: true
	Diff *string `json:"diff"`

	// final score
	// Required: true
	FinalScore *string `json:"finalScore"`

	// ip
	IP string `json:"ip,omitempty"`

	// max memory usage
	// Required: true
	MaxMemoryUsage *int64 `json:"maxMemoryUsage"`

	// max time usage
	// Required: true
	MaxTimeUsage *int64 `json:"maxTimeUsage"`

	// participant
	// Required: true
	Participant *Participant `json:"participant"`

	// precompile checks
	// Required: true
	PrecompileChecks []*AdditionalSolutionCheckResult `json:"precompileChecks"`

	// preliminary score
	// Required: true
	PreliminaryScore *string `json:"preliminaryScore"`

	// problem alias
	// Required: true
	ProblemAlias *string `json:"problemAlias"`

	// problem Id
	// Required: true
	ProblemID *string `json:"problemId"`

	// problem name
	// Required: true
	ProblemName *string `json:"problemName"`

	// run Id
	// Required: true
	RunID *int64 `json:"runId"`

	// source
	// Required: true
	Source *string `json:"source"`

	// status
	// Enum: [WAITING FAILED RUNNING FINISHED]
	Status string `json:"status,omitempty"`

	// submission time
	// Required: true
	SubmissionTime *string `json:"submissionTime"`

	// test file type
	// Required: true
	// Enum: [BINARY TEXT]
	TestFileType *string `json:"testFileType"`

	// time from start
	// Required: true
	TimeFromStart *int64 `json:"timeFromStart"`

	// verdict
	// Required: true
	Verdict *string `json:"verdict"`
}

// Validate validates this full run report
func (m *FullRunReport) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCheckerLog(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCompileLog(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCompiler(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateContestID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateContestName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDiff(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFinalScore(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxMemoryUsage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxTimeUsage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParticipant(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrecompileChecks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePreliminaryScore(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProblemAlias(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProblemID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProblemName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRunID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSource(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSubmissionTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTestFileType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimeFromStart(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVerdict(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FullRunReport) validateCheckerLog(formats strfmt.Registry) error {

	if err := validate.Required("checkerLog", "body", m.CheckerLog); err != nil {
		return err
	}

	for i := 0; i < len(m.CheckerLog); i++ {
		if swag.IsZero(m.CheckerLog[i]) { // not required
			continue
		}

		if m.CheckerLog[i] != nil {
			if err := m.CheckerLog[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("checkerLog" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *FullRunReport) validateCompileLog(formats strfmt.Registry) error {

	if err := validate.Required("compileLog", "body", m.CompileLog); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateCompiler(formats strfmt.Registry) error {

	if err := validate.Required("compiler", "body", m.Compiler); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateContestID(formats strfmt.Registry) error {

	if err := validate.Required("contestId", "body", m.ContestID); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateContestName(formats strfmt.Registry) error {

	if err := validate.Required("contestName", "body", m.ContestName); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateDiff(formats strfmt.Registry) error {

	if err := validate.Required("diff", "body", m.Diff); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateFinalScore(formats strfmt.Registry) error {

	if err := validate.Required("finalScore", "body", m.FinalScore); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateMaxMemoryUsage(formats strfmt.Registry) error {

	if err := validate.Required("maxMemoryUsage", "body", m.MaxMemoryUsage); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateMaxTimeUsage(formats strfmt.Registry) error {

	if err := validate.Required("maxTimeUsage", "body", m.MaxTimeUsage); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateParticipant(formats strfmt.Registry) error {

	if err := validate.Required("participant", "body", m.Participant); err != nil {
		return err
	}

	if m.Participant != nil {
		if err := m.Participant.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("participant")
			}
			return err
		}
	}

	return nil
}

func (m *FullRunReport) validatePrecompileChecks(formats strfmt.Registry) error {

	if err := validate.Required("precompileChecks", "body", m.PrecompileChecks); err != nil {
		return err
	}

	for i := 0; i < len(m.PrecompileChecks); i++ {
		if swag.IsZero(m.PrecompileChecks[i]) { // not required
			continue
		}

		if m.PrecompileChecks[i] != nil {
			if err := m.PrecompileChecks[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("precompileChecks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *FullRunReport) validatePreliminaryScore(formats strfmt.Registry) error {

	if err := validate.Required("preliminaryScore", "body", m.PreliminaryScore); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateProblemAlias(formats strfmt.Registry) error {

	if err := validate.Required("problemAlias", "body", m.ProblemAlias); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateProblemID(formats strfmt.Registry) error {

	if err := validate.Required("problemId", "body", m.ProblemID); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateProblemName(formats strfmt.Registry) error {

	if err := validate.Required("problemName", "body", m.ProblemName); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateRunID(formats strfmt.Registry) error {

	if err := validate.Required("runId", "body", m.RunID); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateSource(formats strfmt.Registry) error {

	if err := validate.Required("source", "body", m.Source); err != nil {
		return err
	}

	return nil
}

var fullRunReportTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["WAITING","FAILED","RUNNING","FINISHED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		fullRunReportTypeStatusPropEnum = append(fullRunReportTypeStatusPropEnum, v)
	}
}

const (

	// FullRunReportStatusWAITING captures enum value "WAITING"
	FullRunReportStatusWAITING string = "WAITING"

	// FullRunReportStatusFAILED captures enum value "FAILED"
	FullRunReportStatusFAILED string = "FAILED"

	// FullRunReportStatusRUNNING captures enum value "RUNNING"
	FullRunReportStatusRUNNING string = "RUNNING"

	// FullRunReportStatusFINISHED captures enum value "FINISHED"
	FullRunReportStatusFINISHED string = "FINISHED"
)

// prop value enum
func (m *FullRunReport) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, fullRunReportTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FullRunReport) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateSubmissionTime(formats strfmt.Registry) error {

	if err := validate.Required("submissionTime", "body", m.SubmissionTime); err != nil {
		return err
	}

	return nil
}

var fullRunReportTypeTestFileTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["BINARY","TEXT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		fullRunReportTypeTestFileTypePropEnum = append(fullRunReportTypeTestFileTypePropEnum, v)
	}
}

const (

	// FullRunReportTestFileTypeBINARY captures enum value "BINARY"
	FullRunReportTestFileTypeBINARY string = "BINARY"

	// FullRunReportTestFileTypeTEXT captures enum value "TEXT"
	FullRunReportTestFileTypeTEXT string = "TEXT"
)

// prop value enum
func (m *FullRunReport) validateTestFileTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, fullRunReportTypeTestFileTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FullRunReport) validateTestFileType(formats strfmt.Registry) error {

	if err := validate.Required("testFileType", "body", m.TestFileType); err != nil {
		return err
	}

	// value enum
	if err := m.validateTestFileTypeEnum("testFileType", "body", *m.TestFileType); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateTimeFromStart(formats strfmt.Registry) error {

	if err := validate.Required("timeFromStart", "body", m.TimeFromStart); err != nil {
		return err
	}

	return nil
}

func (m *FullRunReport) validateVerdict(formats strfmt.Registry) error {

	if err := validate.Required("verdict", "body", m.Verdict); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this full run report based on the context it is used
func (m *FullRunReport) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCheckerLog(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateParticipant(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePrecompileChecks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FullRunReport) contextValidateCheckerLog(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.CheckerLog); i++ {

		if m.CheckerLog[i] != nil {
			if err := m.CheckerLog[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("checkerLog" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *FullRunReport) contextValidateParticipant(ctx context.Context, formats strfmt.Registry) error {

	if m.Participant != nil {
		if err := m.Participant.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("participant")
			}
			return err
		}
	}

	return nil
}

func (m *FullRunReport) contextValidatePrecompileChecks(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.PrecompileChecks); i++ {

		if m.PrecompileChecks[i] != nil {
			if err := m.PrecompileChecks[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("precompileChecks" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *FullRunReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FullRunReport) UnmarshalBinary(b []byte) error {
	var res FullRunReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
