// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HTTPEntity HttpEntity
//
// swagger:model HttpEntity
type HTTPEntity struct {

	// body
	Body interface{} `json:"body,omitempty"`
}

// Validate validates this Http entity
func (m *HTTPEntity) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Http entity based on context it is used
func (m *HTTPEntity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPEntity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPEntity) UnmarshalBinary(b []byte) error {
	var res HTTPEntity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
