// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IDRole Id«Role»
//
// swagger:model Id«Role»
type IDRole struct {

	// checked Id
	// Required: true
	CheckedID *int64 `json:"checkedId"`

	// checked raw external Id
	// Required: true
	CheckedRawExternalID *string `json:"checkedRawExternalId"`

	// external Id
	// Required: true
	ExternalID *ExternalID `json:"externalId"`

	// id
	ID int64 `json:"id,omitempty"`

	// model
	// Required: true
	Model *KClassRole `json:"model"`

	// new
	// Required: true
	New *bool `json:"new"`

	// raw external Id
	RawExternalID string `json:"rawExternalId,omitempty"`

	// uid
	// Format: uuid
	UID strfmt.UUID `json:"uid,omitempty"`
}

// Validate validates this Id role
func (m *IDRole) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCheckedID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCheckedRawExternalID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExternalID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateModel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNew(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IDRole) validateCheckedID(formats strfmt.Registry) error {

	if err := validate.Required("checkedId", "body", m.CheckedID); err != nil {
		return err
	}

	return nil
}

func (m *IDRole) validateCheckedRawExternalID(formats strfmt.Registry) error {

	if err := validate.Required("checkedRawExternalId", "body", m.CheckedRawExternalID); err != nil {
		return err
	}

	return nil
}

func (m *IDRole) validateExternalID(formats strfmt.Registry) error {

	if err := validate.Required("externalId", "body", m.ExternalID); err != nil {
		return err
	}

	if m.ExternalID != nil {
		if err := m.ExternalID.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("externalId")
			}
			return err
		}
	}

	return nil
}

func (m *IDRole) validateModel(formats strfmt.Registry) error {

	if err := validate.Required("model", "body", m.Model); err != nil {
		return err
	}

	if m.Model != nil {
		if err := m.Model.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("model")
			}
			return err
		}
	}

	return nil
}

func (m *IDRole) validateNew(formats strfmt.Registry) error {

	if err := validate.Required("new", "body", m.New); err != nil {
		return err
	}

	return nil
}

func (m *IDRole) validateUID(formats strfmt.Registry) error {
	if swag.IsZero(m.UID) { // not required
		return nil
	}

	if err := validate.FormatOf("uid", "body", "uuid", m.UID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this Id role based on the context it is used
func (m *IDRole) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateExternalID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateModel(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IDRole) contextValidateExternalID(ctx context.Context, formats strfmt.Registry) error {

	if m.ExternalID != nil {
		if err := m.ExternalID.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("externalId")
			}
			return err
		}
	}

	return nil
}

func (m *IDRole) contextValidateModel(ctx context.Context, formats strfmt.Registry) error {

	if m.Model != nil {
		if err := m.Model.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("model")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IDRole) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IDRole) UnmarshalBinary(b []byte) error {
	var res IDRole
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
