// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ParticipantStatus ParticipantStatus
//
// swagger:model ParticipantStatus
type ParticipantStatus struct {

	// contest duration
	ContestDuration string `json:"contestDuration,omitempty"`

	// contest finish time
	ContestFinishTime string `json:"contestFinishTime,omitempty"`

	// contest infinite
	ContestInfinite bool `json:"contestInfinite,omitempty"`

	// contest start time
	ContestStartTime string `json:"contestStartTime,omitempty"`

	// contest state
	ContestState string `json:"contestState,omitempty"`

	// participant finish time
	ParticipantFinishTime string `json:"participantFinishTime,omitempty"`

	// participant left time
	ParticipantLeftTime string `json:"participantLeftTime,omitempty"`

	// participant name
	ParticipantName string `json:"participantName,omitempty"`

	// participant start time
	ParticipantStartTime string `json:"participantStartTime,omitempty"`

	// roles
	Roles []string `json:"roles"`
}

// Validate validates this participant status
func (m *ParticipantStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this participant status based on context it is used
func (m *ParticipantStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ParticipantStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ParticipantStatus) UnmarshalBinary(b []byte) error {
	var res ParticipantStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
