// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RowTitle RowTitle
//
// swagger:model RowTitle
type RowTitle struct {

	// name
	Name string `json:"name,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this row title
func (m *RowTitle) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this row title based on context it is used
func (m *RowTitle) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RowTitle) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RowTitle) UnmarshalBinary(b []byte) error {
	var res RowTitle
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
