// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServiceCapacity ServiceCapacity
//
// swagger:model ServiceCapacity
type ServiceCapacity struct {

	// submissions count
	// Required: true
	SubmissionsCount *int64 `json:"submissionsCount"`
}

// Validate validates this service capacity
func (m *ServiceCapacity) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubmissionsCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceCapacity) validateSubmissionsCount(formats strfmt.Registry) error {

	if err := validate.Required("submissionsCount", "body", m.SubmissionsCount); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this service capacity based on context it is used
func (m *ServiceCapacity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceCapacity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceCapacity) UnmarshalBinary(b []byte) error {
	var res ServiceCapacity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
