// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateParticipantRequest UpdateParticipantRequest
//
// swagger:model UpdateParticipantRequest
type UpdateParticipantRequest struct {

	// displayed name
	DisplayedName string `json:"displayedName,omitempty"`
}

// Validate validates this update participant request
func (m *UpdateParticipantRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update participant request based on context it is used
func (m *UpdateParticipantRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateParticipantRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateParticipantRequest) UnmarshalBinary(b []byte) error {
	var res UpdateParticipantRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
